name: hid
description: A multi-platform plugin which allows an application to interface with USB HID-Class devices on Linux, Windows, Android, and macOS.
version: 0.1.7
repository: https://github.com/rustui/hid/tree/main/hid

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  hid_platform_interface: 
    version: ^0.0.9
    git:
      url: https://github.com/filipsky/hid
      path: hid
  hid_windows: 
    version: ^0.1.1
    git:
      url: https://github.com/filipsky/hid
      path: hid
  hid_macos: 
    version: ^0.1.2
    git:
      url: https://github.com/filipsky/hid
      path: hid
  hid_linux: 
    version: ^0.1.1
    git:
      url: https://github.com/filipsky/hid
      path: hid
  hid_android: ^0.1.1
    version: ^0.1.1
    git:
      url: https://github.com/filipsky/hid
      path: hid

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
      platforms:
        windows:
          default_package: hid_windows
        macos:
          default_package: hid_macos
        android:
          default_package: hid_android
        linux:
          default_package: hid_linux
