name: hid_linux
description: Linux implementation of the hid plugin.
version: 0.1.1
repository: https://github.com/rustui/hid/tree/main/hid_linux
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  hid_platform_interface: 
    version: ^0.0.9
    git:
      url: https://github.com/filipsky/hid
      path: hid_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    implements: hid
    platforms:
      linux:
        dartPluginClass: HidPluginLinux
