name: hid_macos
description: macOS implementation of the hid plugin.
version: 0.1.2
repository: https://github.com/rustui/hid/tree/main/hid_macos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  hid_platform_interface: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    implements: hid
    platforms:
      macos:
        dartPluginClass: HidPluginMacOS